stages:
  prepare_data:
    cmd: python3 ./prepare_data.py
    deps:
      - ./prepare_data.py
      - ./archive/IMDB_Dataset.csv
    params:
      - data
    outs:
      - ./archive/train.csv
      - ./archive/test.csv
  make_features:
    cmd: python3 ./make_features.py
    deps:
      - ./make_features.py
      - ./archive/train.csv
      - ./archive/test.csv
    params:
      - features
    outs:
      - ./archive/train.joblib
      - ./archive/test.joblib
  train:
    cmd: python3 ./train.py
    deps:
      - ./train.py
      - ./archive/train.csv
      - ./archive/train.joblib
    params:
      - train
    outs:
      - ./archive/model.joblib
  evaluate:
    cmd: python3 ./evaluate.py
    deps:
      - ./evaluate.py
      - ./archive/test.csv
      - ./archive/test.joblib
      - ./archive/model.joblib
    params:
      - evaluate
    outs:
      - ./archive/results.yaml